### PR TITLE
Send notices

### PR DESCRIPTION
**Pull request by djmitche**
This flie wasn't properly gofmt'd, so I took care of that in a different commit.

### CODE REVIEW

**Comment by djmitche** [comment]
To be clear, this is completely untested -- I'm battling an Ansible bug to get my dev env set up, but this changed seemed simple enough that it might Just Work.

**Comment by djmitche** [comment]
@jvehent does this look OK?

**Comment by jvehent** [comment]
Simple enough, but I'm missing the reason why we want this change. Care to clarify?

**Comment by djmitche** [comment]
It was mentioned in channel, but maybe you missed it in the spew of other
messages :)

The idea is to only alert for activity in the channel when someone speaks;
notifies are still visible, but most clients will not mark them as
activity.  This will help us _talk_ about beer a little more effectively.

Dustin

2016-09-09 16:29 GMT-04:00 Julien Vehent [:ulfr] notifications@github.com:

**Comment by jvehent** [comment]
That's reasonable. Merging it.

**Pull request merged**
